runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/gcp-code-builder/index.html
    upload: dist/gcp-code-builder/index.html

  - url: /
    static_dir: dist/gcp-code-builder

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE